--FILTERING DATA USING COMPARSION OPERATOR

SELECT *
FROM customers;

-- = Operator  RETRUEVE ALL CUSTOMERS FROM USA
SELECT *
FROM customers
WHERE country = 'USA';

--RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY "<> OPERATOR"
SELECT *
FROM customers
WHERE country <> 'Germany';

--RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY
SELECT *
FROM customers
WHERE country <> 'Germany';

--RETRIEVE ALL CUSTOMERS WITH THE SCORE OF 500 AND MORE
SELECT *
FROM customers
WHERE score >= 500;

--RETRIEVE ALL CUSTOMERS WITH THE SCORE LESS THAN 500 
SELECT *
FROM customers
WHERE score < 500;