--FILTERING DATA USING COMPARSION OPERATOR

SELECT *
FROM customers;

-- = Operator  RETRUEVE ALL CUSTOMERS FROM USA
SELECT *
FROM customers
WHERE country = 'USA';

--RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY "<> OPERATOR"
SELECT *
FROM customers
WHERE country <> 'Germany';

--RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY
SELECT *
FROM customers
WHERE country <> 'Germany';

--RETRIEVE ALL CUSTOMERS WITH THE SCORE OF 500 AND MORE
SELECT *
FROM customers
WHERE score >= 500;

--RETRIEVE ALL CUSTOMERS WITH THE SCORE LESS THAN 500 
SELECT *
FROM customers
WHERE score < 500;

--RETRIEVE ALL CUSTOMERS WITH THE SCORE LESS THAN EQUAL TO 500 
SELECT *
FROM customers
WHERE score <= 500;

/* The company wants to identify employees who are eligible for a performance reward. 
An employee is eligible if their score is greater than 500, country is not Germany, and score is not equal to 0.*/

SELECT *
FROM customers
WHERE score > 500
	  AND country <> 'Germany'
	  AND score <> 0;

	            --  LOGICAL OPERATORS --
/* RETRIEVE ALL CUSTOMERS WHO ARE FROM THE USA AND HAE A SCORE GREATER THAN 500*/
SELECT *
FROM customers
WHERE country = 'USA' AND score > 500;

--RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM THE USA OR HAVE A SCORE GREATER THAN 500
SELECT *
FROM customers
WHERE country = 'USA' OR score > 500;

--RETRIVE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500
SELECT *
FROM customers
WHERE NOT score < 500;

                    --- RANGE OPERATOR ---
--RETRIEVE ALL CUSTOMERS WHOSESCORE FALLS IN THE RANGE BETWEEN 100 AND 500
SELECT *
FROM customers
WHERE score BETWEEN 100 AND 500;

                   --- MEMBERSHIP OPERATOR ---
--RETRIEVE ALL CUSTOMERS FROM EITHER GERMANY OR USA
SELECT *
FROM customers
WHERE country IN ('Germany','USA');

SELECT *
FROM customers
WHERE country NOT IN ('Germany','USA');

                   --- SEARCH OPERATOR ---
--FIND ALL CUSTOMERS WHOSE NAME STARTS WITH 'M'
SELECT *
FROM customers
WHERE first_name LIKE 'M%';

--FIND ALL CUSTOMERS WHOSE NAME ENDS WITH 'N'
SELECT *
FROM customers
WHERE first_name LIKE '%n';

--FIND ALL CUSTOMERS WHOSE FIRST NAME CONATINS 'R'
SELECT *
FROM customers
WHERE first_name LIKE '%r%';

--FIND ALL CUSTOMERS WHOSE FIRST NAME HAS 'R' IN THE THIRD POSITION
SELECT *
FROM customers
WHERE first_name LIKE '__r%';