/* RETRIEVE ALL DATA OF CUSTOMERS
SELECT *
FROM customers;

--RETRIEVES EACH CUSTOMER'S NAME,COUNTRY AND SCORE
SELECT 
	first_name,
	country,
	score
FROM customers;

--RETRIEVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0
SELECT
	first_name,
	country,
	score
FROM customers
WHERE score != 0;

--RETRIEVE CUSTOMERS FROM GERMANY
SELECT *
FROM customers
WHERE country = 'Germany';

--RETRIVE ALL CUSTOMERS AND SORT THE VALUES BY THE HIGHEST SCORE FIRST
SELECT *
FROM customers
ORDER BY score DESC;

--RETRIVE ALL CUSTOMERS AND SORT THE VALUES BY THE HIGHEST SCORE FIRST
SELECT *
FROM customers
ORDER BY score ;

--RETRIVE ALL CUSTOMERS AND SORT THE VALUES BY THE COUNTRY AND THEN BY HIGHEST SCORE FIRST
SELECT *
FROM customers
ORDER BY country ASC,score DESC;

--FIND THE TOTAL SCORE FOR EACH COUNTRY
SELECT 
	country,
	SUM(score) AS total_score
FROM customers
GROUP BY country
ORDER BY total_score DESC;


--FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS FOR EACH COUNTRY
SELECT
	country ,
	SUM(score) AS total_score,
	COUNT(id) AS total_customers
FROM customers
GROUP BY country;

--FIND THE AVERAGE SCORE FOR EACH COUNTRY CONSIDERING ONLY CUSTOMERS WITH A SC0RE NOT EQUAL TO 0
SELECT
	country,
	AVG(score) AS average_score
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430;

--RETURN UNIQUE LIST OF ALL COUNTRIES
SELECT DISTINCT
	country
FROM customers

--RETRIEVE ONLY 3 CUSTOMERS
SELECT TOP 3 *
FROM customers

--RETRIEVE TOP 3 CUSTOMERS WITH THE HIGHEST SCORE
SELECT TOP 3 *
FROM customers
ORDER BY score DESC;

--RETRIEVE LOWEST 2 CUSTOMERS BASED ON SCORE
SELECT TOP 2 *
FROM customers
ORDER BY score;*/

--STATIC VALUES
SELECT 
	id,
	first_name,
	'New_Customer' AS customer_type
FROM customers