--DDL COMMANDS
--CREATE COMMAND

CREATE TABLE persons(
	id INT NOT NULL,
	name VARCHAR(20) NOT NULL,
	birth_date DATE,
	phone VARCHAR(15) NOT NULL,
	CONSTRAINT pk_persons PRIMARY KEY (id)
);

--ALTER COMMAND

ALTER TABLE persons
ADD email VARCHAR(50) NOT NULL;

--DROP COMMAND

ALTER TABLE persons
DROP COLUMN phone;

SELECT *
FROM persons;

--DELETE THE TABLE PERSON FROM DATABASE

--DELETE TABLE persons;