--FILTERING DATA USING COMPARSION OPERATOR

SELECT *
FROM customers;

-- = Operator  RETRUEVE ALL CUSTOMERS FROM USA
SELECT *
FROM customers
WHERE country = 'USA';

--RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY "<> OPERATOR"
SELECT *
FROM customers
WHERE country <> 'Germany';