CREATE DATABASE STARTERSQL;
USE STARTERSQL;
CREATE TABLE USER(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME_1 VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
GENDER ENUM ('MALE','FEMALE','OTHERS'),
DATE_OF_BIRTH  DATETIME,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM USER;

