-- FIND ALL CUSTOMERS WHOSE FIRST NAME STARTS WITH M --
SELECT *
FROM customers
WHERE first_name LIKE 'M%'

-- FIND ALL CUSTOMERS WHOSE FIRST NAME  ENDS WITH N --
SELECT *
FROM customers
WHERE first_name LIKE '%n' 

-- FIND ALL CUSTOMERS WHOSE FIRST NAME CONTAINS AN R --
SELECT *
FROM customers
WHERE first_name LIKE '%r%'

-- -- FIND ALL CUSTOMERS WHOSE FIRST NAME HAS 'R' IN THE THIRD POSITION----
SELECT *
FROM customers
WHERE first_name LIKE '__r%'